"""Follow-up question suggestions for the research chat's pills.

After every answer the pills under the thread become follow-up questions.
A small hosted model (the "neural" path) writes them from the question,
the answer and the titles of the sources used. If the model is unavailable
or its output is unusable, deterministic templates built from the key terms
of the conversation take over, so the pills always update.

Questions are generated by a language model rather than a Markov chain on
purpose: chain-generated questions come out ungrammatical.
"""

import json
import os
import re
from typing import Sequence

from pydantic import BaseModel, Field

from app.services.research_chat import _groq_models, groq_complete

DEFAULT_SUGGEST_MODEL = "openai/gpt-oss-20b"
DEFAULT_SUGGEST_MAX_WAIT_SECONDS = 5.0
SUGGEST_MAX_TOKENS = 600

MIN_QUESTION_CHARS = 12
MAX_QUESTION_CHARS = 120

ANSWER_CHARS_IN_PROMPT = 3000

SYSTEM_PROMPT = (
    "You write follow-up questions for a literature-research chat. "
    "Return only a JSON array of strings."
)

PROMPT = """Given the user's question, the assistant's answer and the titles of the
sources used, write exactly {count} short follow-up questions the user is likely
to ask next.

Rules:
- One self-contained sentence each, under 110 characters, ending with "?".
- Each must be answerable from academic papers on this topic.
- Do not repeat the question already asked; vary the angle (compare, method,
  limitation, evidence, gap).
- Do not use citation numbers or bracketed references.

USER QUESTION:
{question}

ASSISTANT ANSWER:
{answer}

SOURCES USED:
{titles}
"""


class SuggestionRequest(BaseModel):
    question: str = Field(min_length=1, max_length=4000)
    answer: str = Field(default="", max_length=20000)
    source_titles: list[str] = Field(default_factory=list, max_length=12)
    count: int = Field(default=3, ge=1, le=5)


class SuggestionResponse(BaseModel):
    suggestions: list[str]
    used_fallback: bool = False


# ------------------------------------------------------------------
# Key terms (for the template fallback)
# ------------------------------------------------------------------

_STOPWORDS = set(
    """a about above after again against all also am an and any are as at be
    because been before being below between both but by can could did do does
    doing down during each few for from further had has have having he her here
    hers him his how i if in into is it its itself just me more most my no nor
    not now of off on once only or other our out over own same she should so
    some such than that the their them then there these they this those through
    to too under until up very was we were what when where which while who whom
    why will with would you your may might must shall likely often however
    therefore thus whereas although among per via""".split()
)

# Words every research answer uses; they say nothing about the topic.
_GENERIC = set(
    """paper papers study studies result results source sources author authors
    research work works approach finding findings show shows shown showed find
    found use used using based report reports reported suggest suggests
    suggested evidence overall several many various different within across
    provide provides provided including include includes""".split()
)

_WORD = re.compile(r"[A-Za-z][A-Za-z'\-]+")
_CLAUSE_BREAK = re.compile(r"[.,;:!?()\[\]\n]+")


def _content_tokens(clause: str) -> list[str | None]:
    """Lower-cased words, with None standing for a stopword/generic gap."""

    tokens: list[str | None] = []

    for word in _WORD.findall(clause):
        lowered = word.lower().strip("'-")

        if lowered in _STOPWORDS or lowered in _GENERIC or len(lowered) < 3:
            tokens.append(None)
        else:
            tokens.append(lowered)

    return tokens


def key_terms(text: str, k: int = 3) -> list[str]:
    """Top topic phrases: repeated bigrams first, then repeated or long words."""

    unigrams: dict[str, int] = {}
    bigrams: dict[str, int] = {}
    first_seen: dict[str, int] = {}
    order = 0

    for clause in _CLAUSE_BREAK.split(text or ""):
        tokens = _content_tokens(clause)

        for index, token in enumerate(tokens):
            if token is None:
                continue

            unigrams[token] = unigrams.get(token, 0) + 1
            first_seen.setdefault(token, order)
            order += 1

            nxt = tokens[index + 1] if index + 1 < len(tokens) else None

            if nxt is not None:
                phrase = f"{token} {nxt}"
                bigrams[phrase] = bigrams.get(phrase, 0) + 1
                first_seen.setdefault(phrase, order)

    candidates: list[tuple[int, int, int, str]] = []

    for phrase, count in bigrams.items():
        if count >= 2:
            candidates.append((count * 2, len(phrase), -first_seen[phrase], phrase))

    for word, count in unigrams.items():
        if count >= 2 or len(word) >= 7:
            candidates.append((count, len(word), -first_seen[word], word))

    candidates.sort(reverse=True)

    chosen: list[str] = []

    for _, _, _, term in candidates:
        if any(term == c or term in c.split() for c in chosen):
            continue

        chosen.append(term)

        if len(chosen) == k:
            break

    return chosen


# ------------------------------------------------------------------
# Templates (always available)
# ------------------------------------------------------------------

_TEMPLATES = (
    "How do the sources compare on {a}?",
    "What are the main limitations of the work on {a}?",
    "Which methods are used to study {b}?",
    "What evidence supports the claims about {a}?",
    "What gaps remain in research on {b}?",
)


def template_suggestions(terms: Sequence[str], count: int) -> list[str]:
    first = terms[0] if terms else "this topic"
    second = terms[1] if len(terms) > 1 else first

    return [
        template.format(a=first, b=second) for template in _TEMPLATES[:count]
    ]


# ------------------------------------------------------------------
# Model output
# ------------------------------------------------------------------


def _parse_questions(raw: str) -> list[str]:
    match = re.search(r"\[.*\]", raw, flags=re.S)

    if not match:
        return []

    try:
        data = json.loads(match.group(0))
    except ValueError:
        return []

    return [item for item in data if isinstance(item, str)] if isinstance(data, list) else []


def _clean(questions: Sequence[str], asked: str) -> list[str]:
    seen = {re.sub(r"\W+", " ", asked).strip().lower()}
    cleaned: list[str] = []

    for item in questions:
        text = re.sub(r"\s+", " ", item).strip().strip('"')

        if not text.endswith("?"):
            text = text.rstrip(".!") + "?"

        key = re.sub(r"\W+", " ", text).strip().lower()

        if not MIN_QUESTION_CHARS <= len(text) <= MAX_QUESTION_CHARS:
            continue

        if key in seen:
            continue

        seen.add(key)
        cleaned.append(text)

    return cleaned


def _suggest_models() -> list[str]:
    primary = os.getenv("GROQ_SUGGEST_MODEL") or DEFAULT_SUGGEST_MODEL
    chain = [primary]

    # The fallbacks only: the main answer model's quota is left alone.
    for name in _groq_models()[1:]:
        if name not in chain:
            chain.append(name)

    return chain


def _max_wait() -> float:
    try:
        return max(
            0.0,
            float(
                os.getenv(
                    "GROQ_SUGGEST_MAX_WAIT_SECONDS",
                    DEFAULT_SUGGEST_MAX_WAIT_SECONDS,
                )
            ),
        )
    except ValueError:
        return DEFAULT_SUGGEST_MAX_WAIT_SECONDS


_REFERENCE_BLOCK = re.compile(r"\n\n(?:References|Works Cited|Bibliography)\n.*", re.S)


def _answer_body(answer: str) -> str:
    """The prose of a styled answer, without its appended reference list."""

    return _REFERENCE_BLOCK.sub("", answer).strip()


def suggest_followups(request: SuggestionRequest) -> SuggestionResponse:
    body = _answer_body(request.answer)
    terms = key_terms(f"{request.question}. {body}", 2)

    prompt = PROMPT.format(
        count=request.count,
        question=request.question.strip(),
        answer=body[:ANSWER_CHARS_IN_PROMPT] or "(none)",
        titles="\n".join(f"- {t}" for t in request.source_titles) or "(none)",
    )

    from_model: list[str] = []

    try:
        raw = groq_complete(
            prompt,
            system=SYSTEM_PROMPT,
            max_tokens=SUGGEST_MAX_TOKENS,
            models=_suggest_models(),
            max_wait=_max_wait(),
        )
        from_model = _clean(_parse_questions(raw), request.question)[: request.count]
    except RuntimeError as error:
        print(f"Chat suggestions fell back to templates: {error}")

    suggestions = list(from_model)

    for candidate in template_suggestions(terms, len(_TEMPLATES)):
        if len(suggestions) >= request.count:
            break

        if candidate not in suggestions:
            suggestions.append(candidate)

    return SuggestionResponse(
        suggestions=suggestions[: request.count],
        used_fallback=not from_model,
    )
