"""
SQLAlchemy ORM models for the Academic Paper Repository & Recommendation System.

Tables:
    - User            : accounts & auth records
    - Paper           : 9 metadata fields + validation + precomputed vectors
    - PersonalLibrary : join table linking users to papers they've saved
"""

from datetime import datetime

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    UniqueConstraint,
)

from sqlalchemy.orm import relationship, declarative_base


Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    username = Column(
        String(100),
        unique=True,
        nullable=False,
        index=True,
    )

    email = Column(
        String(150),
        unique=True,
        nullable=False,
        index=True,
    )

    password_hash = Column(
        String(255),
        nullable=False,
    )

    is_admin = Column(
        Boolean,
        default=False,
        nullable=False,
    )
    # Library-side site editor account. The local default user and any
    # future visitor accounts stay False; only the seeded admin is True.

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    library_entries = relationship(
        "PersonalLibrary",
        back_populates="user",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return (
            f"<User id={self.id} "
            f"username={self.username!r}>"
        )


class Paper(Base):
    __tablename__ = "papers"

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    # ---------------------------------------------------------
    # 9 core metadata fields
    # ---------------------------------------------------------
    # These fields follow the thesis specification.

    title = Column(
        String(500),
        nullable=False,
    )

    author = Column(
        String(300),
        nullable=True,
    )

    abstract = Column(
        Text,
        nullable=True,
    )

    keywords = Column(
        Text,
        nullable=True,
    )
    # Stores author-provided or YAKE-generated keywords.
    # Example:
    # "machine learning, recommendation system, text mining"

    publication_year = Column(
        Integer,
        nullable=True,
    )

    doi = Column(
        String(100),
        nullable=True,
    )

    subject_category = Column(
        String(200),
        nullable=True,
    )

    document_type = Column(
        String(100),
        nullable=True,
    )

    citation_count = Column(
        Integer,
        nullable=True,
    )

    # ---------------------------------------------------------
    # Keyword extraction tracking
    # ---------------------------------------------------------
    # Indicates where the saved keywords came from:
    #
    # "author" -> extracted from the PDF's keyword section
    # "yake"   -> generated automatically by YAKE
    # None     -> no keywords were found or generated

    keywords_source = Column(
        String(20),
        nullable=True,
    )

    # True when the keywords were generated by YAKE.
    # False when the keywords came from the author or are absent.

    keywords_generated = Column(
        Boolean,
        default=False,
        nullable=False,
    )

    # ---------------------------------------------------------
    # Validation tracking
    # ---------------------------------------------------------
    # A paper stays stored even if invalid.
    # This field only determines whether the paper can be used
    # by the Recommendation Layer.

    is_valid_for_recommendation = Column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
    )
# Human-readable trace of what metadata_enrichment.py filled in and
    # from which source, e.g. "abstract <- semantic_scholar (confidence 0.76)".
    # Optional -- see scripts/migrate_add_enrichment_notes.py.
    missing_fields = Column(
        Text,
        nullable=True,
    )
    enrichment_notes = Column(
    Text,
    nullable=True,
)
   
    
    # Example:
    # "abstract, publication_year"

    # ---------------------------------------------------------
    # Upload provenance
    # ---------------------------------------------------------
    # Used by the PDF automatic extraction workflow.

    source_filename = Column(
        String(300),
        nullable=True,
    )
    # Original uploaded PDF filename.

    extraction_method = Column(
        String(20),
        nullable=True,
    )
    # Possible values:
    # "auto"   -> extracted from PDF
    # "manual" -> entered or corrected manually

    stored_path = Column(
        String(500),
        nullable=True,
    )
    # Example:
    # "papers/104.pdf"

    # ---------------------------------------------------------
    # Text preparation and recommendation vectors
    # ---------------------------------------------------------
    # prepared_text contains:
    #
    # Title + Abstract + Keywords
    #
    # It is normalized before being used by TF-IDF and SBERT.

    prepared_text = Column(
        Text,
        nullable=True,
    )

    tfidf_vector = Column(
        Text,
        nullable=True,
    )
    # JSON-encoded list[float].

    sbert_vector = Column(
        Text,
        nullable=True,
    )
    # JSON-encoded list[float].

    # ---------------------------------------------------------
    # Timestamps
    # ---------------------------------------------------------

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    # ---------------------------------------------------------
    # Relationships
    # ---------------------------------------------------------

    library_entries = relationship(
        "PersonalLibrary",
        back_populates="paper",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return (
            f"<Paper id={self.id} "
            f"title={self.title[:40]!r}>"
        )


class PersonalLibrary(Base):
    __tablename__ = "personal_library"

    __table_args__ = (
        # A user can only save the same paper once.
        UniqueConstraint(
            "user_id",
            "paper_id",
            name="uq_user_paper",
        ),
    )

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )

    paper_id = Column(
        Integer,
        ForeignKey("papers.id"),
        nullable=False,
        index=True,
    )

    saved_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    user = relationship(
        "User",
        back_populates="library_entries",
    )

    paper = relationship(
        "Paper",
        back_populates="library_entries",
    )

    def __repr__(self):
        return (
            f"<PersonalLibrary "
            f"user_id={self.user_id} "
            f"paper_id={self.paper_id}>"
        )


class BattleRun(Base):
    """One pipeline-battle run on the Evaluation page.

    Records which pipeline won the run (by independence-weighted
    consensus) so the frontend can tally wins over time.
    """

    __tablename__ = "battle_runs"

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    query = Column(Text, nullable=True)
    seed_paper_id = Column(Integer, nullable=True)
    top_k = Column(Integer, nullable=False)

    winner_pipeline_id = Column(
        String(50),
        nullable=False,
        index=True,
    )

    winner_metric = Column(
        String(50),
        nullable=False,
        default="independence_weighted_consensus",
    )

    winner_value = Column(Float, nullable=True)
    avg_consensus_rank = Column(Float, nullable=True)

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )

    def __repr__(self):
        return (
            f"<BattleRun id={self.id} "
            f"winner={self.winner_pipeline_id!r} "
            f"created_at={self.created_at}>"
        )


class PaperCitation(Base):
    """One external citation relation of a local Paper (P2-A).

    Rows come from OpenAlex and power bibliographic coupling
    (shared references) and co-citation (shared citers) in the
    similar-papers graph.

    direction:
        "cites"    -> external_work_id is a work this paper cites
                      (OpenAlex referenced_works)
        "cited_by" -> external_work_id is a work that cites this
                      paper (OpenAlex cited_by_api_url results)

    matched_paper_id is set when the external work's DOI resolves
    to a local Paper, so two local papers can couple through
    different OpenAlex ids for the same work.
    """

    __tablename__ = "paper_citations"

    __table_args__ = (
        # One row per (paper, direction, external work); refresh
        # deletes + reinserts a direction, and this constraint keeps
        # a hand-written duplicate from slipping in.
        UniqueConstraint(
            "paper_id",
            "direction",
            "external_work_id",
            name="uq_paper_citation_direction_work",
        ),
    )

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    paper_id = Column(
        Integer,
        ForeignKey("papers.id"),
        nullable=False,
        index=True,
    )

    direction = Column(
        String(16),
        nullable=False,
    )
    # "cites" | "cited_by"

    external_work_id = Column(
        String(64),
        nullable=False,
    )
    # Normalized OpenAlex work id, e.g. "W2741809807".

    external_doi = Column(
        String(255),
        nullable=True,
    )
    # Only the cited_by payload usually carries DOIs; OpenAlex
    # referenced_works are bare ids, so "cites" rows often have
    # external_doi=None.

    matched_paper_id = Column(
        Integer,
        ForeignKey("papers.id"),
        nullable=True,
        index=True,
    )
    # Local Paper whose DOI equals external_doi, if any.

    source = Column(
        String(32),
        default="openalex",
        nullable=False,
    )

    fetched_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    def __repr__(self):
        return (
            f"<PaperCitation id={self.id} "
            f"paper_id={self.paper_id} "
            f"direction={self.direction!r} "
            f"work={self.external_work_id!r}>"
        )


class Announcement(Base):
    """One library-facing announcement, written by the site admin.

    Announcements show on the Library Home page (and only there); the
    admin toggles them on/off instead of deleting when they go stale,
    so the history stays around for re-use.
    """

    __tablename__ = "announcements"

    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    title = Column(
        String(200),
        nullable=False,
    )

    body = Column(
        Text,
        nullable=False,
    )

    level = Column(
        String(20),
        default="info",
        nullable=False,
    )
    # "info" | "important" | "event"

    active = Column(
        Boolean,
        default=True,
        nullable=False,
        index=True,
    )

    position = Column(
        Integer,
        default=0,
        nullable=False,
    )
    # Lower renders first; the admin moves announcements up/down.

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    def __repr__(self):
        return (
            f"<Announcement id={self.id} "
            f"title={self.title!r} active={self.active}>"
        )


class SiteSetting(Base):
    """Key/value store for site-wide configuration.

    Today it holds `library_features` (per-feature shown/locked/hidden
    states for Library Mode) and `admin_token_secret` (the HMAC key
    behind admin session tokens, generated once on first run).
    """

    __tablename__ = "site_settings"

    key = Column(
        String(100),
        primary_key=True,
    )

    value = Column(
        Text,
        nullable=False,
    )

    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    def __repr__(self):
        return f"<SiteSetting key={self.key!r}>"